name: Pack new release

on:
  pull_request:
    branches:
      - dev

jobs:
  pack:
    name: Pack Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Node Env
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Lint & Build
        run: |
          npm install
          npm run lint
          npm run build-production

      - name: ZIP Release
        run: |
          apt-get update && apt-get install -y zip
          cd dist/ && zip -r release.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr-${{ github.sha }}-chromium-firefox.zip
          path: dist/release.zip
          retention-days: 90
