name: Pack new release

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: Tag Name
        required: true

jobs:
  pack:
    name: Pack Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Node Env
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Lint & Build
        run: |
          git clone https://github.com/SevenTV/Typings.git
          npm install
          npm run lint
          npm run build-production

      - name: ZIP Release
        run: |
          apt-get update && apt-get install -y zip
          cd dist/ && zip -r release.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: dist/release.zip
          retention-days: 3

  release:
    name: Publish Build Artifact to Release
    runs-on: ubuntu-latest
    needs: [pack]

    steps:
      - name: Download Artifacvt
        uses: actions/download-artifact@v2
        with:
          name: build-output

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tagName }}
          release_name: Version ${{ github.event.inputs.tagName }}
          draft: true
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: 7tv-${{ github.event.inputs.tagName }}-chromium-firefox.zip
          asset_content_type: application/zip
