name: Pack new release

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: Tag Name
        required: true

jobs:
  pack:
    name: Pack Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Node Env
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Lint
        run: |
          yarn
          yarn lint

      - name: Build
        run: |
          yarn build-prod-chromium
          yarn build-prod-firefox

      - name: ZIP Releases
        run: |
          apt-get update && apt-get install -y zip
          cd dist/chromium/ && zip -r release-chromium.zip . && cd ../../
          cd dist/firefox/ && zip -r release-firefox.zip .

      - name: Upload Artifact (Chromium)
        uses: actions/upload-artifact@v2
        with:
          name: ext-chromium
          path: dist/chromium/release-chromium.zip
          retention-days: 60

      - name: Upload Artifact (Firefox)
        uses: actions/upload-artifact@v2
        with:
          name: ext-firefox
          path: dist/firefox/release-firefox.zip
          retention-days: 60

  release:
    name: Publish Build Artifact to Release
    runs-on: ubuntu-latest
    needs: [pack]

    steps:
      - name: Download Artifact (Chromium)
        uses: actions/download-artifact@v2
        with:
          name: ext-chromium
      - name: Download Artifact (Firefox)
        uses: actions/download-artifact@v2
        with:
          name: ext-firefox

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tagName }}
          release_name: Version ${{ github.event.inputs.tagName }}
          draft: true
          prerelease: false

      - name: Upload Release Asset (Chromium)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url }}
          asset_path: ./release-chromium.zip
          asset_name: 7tv-${{ github.event.inputs.tagName }}-chromium.zip
          asset_content_type: application/zip

      - name: Upload Release Asset (Firefox)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url }}
          asset_path: ./release-firefox.zip
          asset_name: 7tv-${{ github.event.inputs.tagName }}-firefox.zip
          asset_content_type: application/zip
